const municipalities = [
  { value: "Deçan", text: "Deçan" },
  { value: "Gjakovë", text: "Gjakovë" },
  { value: "Gllogoc", text: "Gllogoc" },
  { value: "Gjilan", text: "Gjilan" },
  { value: "Dragash", text: "Dragash" },
  { value: "Istog", text: "Istog" },
  { value: "Kaçanik", text: "Kaçanik" },
  { value: "Klinë", text: "Klinë" },
  { value: "Fushë Kosovë", text: "Fushë Kosovë" },
  { value: "Kamenicë", text: "Kamenicë" },
  { value: "Leposaviq", text: "Leposaviq" },
  { value: "Lipjan", text: "Lipjan" },
  { value: "Obiliq", text: "Obiliq" },
  { value: "Rahovec", text: "Rahovec" },
  { value: "Pejë", text: "Pejë" },
  { value: "Podujevë", text: "Podujevë" },
  { value: "Prishtinë", text: "Prishtinë" },
  { value: "Prizren", text: "Prizren" },
  { value: "Skënderaj", text: "Skënderaj" },
  { value: "Shtime", text: "Shtime" },
  { value: "Shtërpcë", text: "Shtërpcë" },
  { value: "Suharekë", text: "Suharekë" },
  { value: "Ferizaj", text: "Ferizaj" },
  { value: "Viti", text: "Viti" },
  { value: "Vushtrri", text: "Vushtrri" },
  { value: "Zubin Potok", text: "Zubin Potok" },
  { value: "Zveçan", text: "Zveçan" },
  { value: "Malishevë", text: "Malishevë" },
  { value: "Novobërdë", text: "Novobërdë" },
  { value: "Mitrovicë e Veriut", text: "Mitrovicë e Veriut" },
  { value: "Mitrovicë e Jugut", text: "Mitrovicë e Jugut" },
  { value: "Junik", text: "Junik" },
  { value: "Hani i Elezit", text: "Hani i Elezit" },
  { value: "Mamushë", text: "Mamushë" },
  { value: "Graçanicë", text: "Graçanicë" },
  { value: "Ranillug", text: "Ranillug" },
  { value: "Partesh", text: "Partesh" },
  { value: "Kllokot", text: "Kllokot" },
];

export default municipalities;
